spring:
  cloud:
    nacos:
      discovery:
        server-addr: 158.51.124.146:8848
    #前端项目，http://localhost:88/api/captcha.jpg 转成 http://localhost:8080/mall-admin/captcha.jpg
    gateway:
      routes:
        - id: test_baidu_routes
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_qq_routes
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: admin_route
          uri: lb://blog-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /blog-admin/$\{segment}
