server:
  tomcat:
    uri-encoding: UTF-8
  port: 9000
#  servlet:
#    context-path: /blog-server

spring:
  profiles:
    # 环境 dev|test|prod
    active: dev
  application:
    name: blog-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.81:8848
  redis:
    host: 158.51.124.146
    port: 6379
    password: aijiahao
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.aijiahao.blog.server.entity
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
